---
on:
  push:
    tags:
      - "v*"

name: "Release"
jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/release-github-actions@v6
        with:
          CLEAN_TARGETS: .[!.]*,__tests__,docs,lib,node_modules,src,*.js,*.ts,*.json,*.lock,*.yml,*.yaml
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
